// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SgalApp.Infrastructure.StoredProcedures
{
    public partial class sp_Emp_ValidaAccesoResult
    {
        public bool? Acceso_Valido { get; set; }
        public bool? Cambio_Clave { get; set; }
        [StringLength(100)]
        public string Mensaje { get; set; }
    }
}
