// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SgalApp.Infrastructure.StoredProcedures
{
    public partial class sp_Emp_Crea_UsuarioEmpleadoResult
    {
        public int? Id_Usuario_Creado { get; set; }
        [StringLength(100)]
        public string Nombre_Usuario_Creado { get; set; }
        [StringLength(28)]
        public string Mensaje { get; set; }
    }
}
