// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Infraestructura.Entities.Sp;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Infraestructura.Entities.Sp
{
    public partial interface ISpSieteVidasContextProcedures
    {
        Task<List<sp_Emp_CambiaClaveResult>> sp_Emp_CambiaClaveAsync(int? iDUSUARIO, string pASSACTUAL, string pASSNUEVA, bool? eSADMIN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_Emp_Crea_UsuarioEmpleadoResult>> sp_Emp_Crea_UsuarioEmpleadoAsync(int? rUT, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_Emp_ValidaAccesoResult>> sp_Emp_ValidaAccesoAsync(int? iDUSUARIO, string pASS, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
