// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Infraestructura.Entities.Sp
{
    public partial class sp_Emp_CambiaClaveResult
    {
        public int Resultado { get; set; }
        [StringLength(34)]
        public string Mensaje { get; set; }
    }
}
