// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Infraestructura.Entities.Sp;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Infraestructura.Entities.Sp
{
    public partial class SpSieteVidasContext
    {
        private ISpSieteVidasContextProcedures _procedures;

        public virtual ISpSieteVidasContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new SpSieteVidasContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ISpSieteVidasContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class SpSieteVidasContextProcedures : ISpSieteVidasContextProcedures
    {
        private readonly SpSieteVidasContext _context;

        public SpSieteVidasContextProcedures(SpSieteVidasContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_Emp_CambiaClaveResult>> sp_Emp_CambiaClaveAsync(int? iDUSUARIO, string pASSACTUAL, string pASSNUEVA, bool? eSADMIN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDUSUARIO",
                    Value = iDUSUARIO ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PASSACTUAL",
                    Size = 100,
                    Value = pASSACTUAL ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PASSNUEVA",
                    Size = 100,
                    Value = pASSNUEVA ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ESADMIN",
                    Value = eSADMIN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_Emp_CambiaClaveResult>("EXEC @returnValue = [dbo].[sp_Emp_CambiaClave] @IDUSUARIO = @IDUSUARIO, @PASSACTUAL = @PASSACTUAL, @PASSNUEVA = @PASSNUEVA, @ESADMIN = @ESADMIN", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_Emp_Crea_UsuarioEmpleadoResult>> sp_Emp_Crea_UsuarioEmpleadoAsync(int? rUT, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "RUT",
                    Value = rUT ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_Emp_Crea_UsuarioEmpleadoResult>("EXEC @returnValue = [dbo].[sp_Emp_Crea_UsuarioEmpleado] @RUT = @RUT", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_Emp_ValidaAccesoResult>> sp_Emp_ValidaAccesoAsync(int? iDUSUARIO, string pASS, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDUSUARIO",
                    Value = iDUSUARIO ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PASS",
                    Size = 100,
                    Value = pASS ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_Emp_ValidaAccesoResult>("EXEC @returnValue = [dbo].[sp_Emp_ValidaAcceso] @IDUSUARIO = @IDUSUARIO, @PASS = @PASS", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
